### PR TITLE
Add nydus image artifact

### PR DESCRIPTION
**Pull request by liubogithub**
Artifact manifest is a nice way to offer the ability of enhancing
registry as well as applying minimum modifications to client tools.

Nydus image is an alternative representation of container image,
providing benefits like making starting containers as fast as
possible.

We'd like to have nydus image persist as a new artifact.

Signed-off-by: Liu Bo <bo.liu@linux.alibaba.com>
Signed-off-by: Peng Tao <tao.peng@linux.alibaba.com>

@bergwolf

### CODE REVIEW

**Comment by liubogithub** [comment]
@SteveLasker Hi Steve, could you please take a look at this?
I've updated it to using [manifest] only.

**Comment by SteveLasker** [comment]
I’m hoping to get the artifact.manifest spec out this week and I’ll add Nydus as an example along SBoMs. 
Do you know if Harbor is planing on implementing support?

**Comment by bergwolf** [comment]
@SteveLasker We are working with Harbor folks to add Nydus support and we are still using the `os.feature` hack for compatibility reasons. We haven't talked about the artifact manifest spec yet. But IMO it'd be great to see Harbor supporting it. We need both registry and runtime side support to run the new spec. Will ask for their opinions in our next meeting on Friday.

**Comment by SteveLasker** [comment]
I incorporated the nydus example in the latest PR, which includes spec details.

**Pull request closed without merging**
